activityScheduleAssigner: standard
carOwnership:
  engine: data_clayton/parameters/Archive/SociodemographicCoefficients.txt
  ownership: data_clayton/parameters/Archive/CarOwnershipModelParameter.txt
  segment: data_clayton/parameters/LogitBasedCarSegmentModelParameter.txt
#mobilityProviders:
commuterTicket: data_clayton/parameters/TransitPassParameter.txt
dataSource: !file
  demandDataFolder: output/demand-data
  matrixConfigurationFile: data_clayton/matrices/matrix-configuration.yaml
  attractivityDataFile: data_clayton/zone_properties/attractivities.csv
  zonePropertiesDataFile: data_clayton/zone_properties/zone-properties.csv
  parkingFacilitiesDataFile: data_clayton/zone_properties/parking-facilities.csv
  bikeSharingPropertiesDataFile: data_clayton/zone_properties/bikesharing-properties.csv
  carSharingPropertiesDataFile: data_clayton/zone_properties/carsharing-properties.csv
  carSharingStationsDataFile: data_clayton/zone_properties/carsharing-stations.csv
  carSharingFreeFloatingDataFile: data_clayton/zone_properties/carsharing-free-floating.csv
  #charging: unlimited
  defaultChargingPower: data_clayton/parameters/ChargingPower.txt
  zoneRepositoryFolder: output/zone-repository/
demographyData:
  age_f: data_clayton/zone_properties/demography-ipf.csv
  age_m: data_clayton/zone_properties/demography-ipf.csv
  dom_code: data_clayton/zone_properties/demography-ipf.csv
  job: data_clayton/zone_properties/demography-ipf.csv
#numberOfZones: 2147483647
panelData: data_clayton/clayton/clayton-population.csv
resultFolder: results/population-synthesis
seed: 77859
synthesisZoneProperties: data_clayton/zone_properties/synthesis-zone-properties.csv
visumFile: data_clayton/clayton/Clayton12km.net
pois: data_clayton/zone_properties/Clayton_12km_Opportunity_Poi.csv
#experimental:
#  parameter1: 1
#  parameter2: 2
