dataSource: !file
  demandDataFolder: output/demand-data
  matrixConfigurationFile: data_clayton/matrices/matrix-configuration.yaml
  attractivityDataFile: data_clayton/zone_properties/attractivities.csv
  zonePropertiesDataFile: data_clayton/zone_properties/zone-properties.csv
  parkingFacilitiesDataFile: data_clayton/zone_properties/parking-facilities.csv
  bikeSharingPropertiesDataFile: data_clayton/zone_properties/bikesharing-properties.csv
  carSharingPropertiesDataFile: data_clayton/zone_properties/carsharing-properties.csv
  carSharingStationsDataFile: data_clayton/zone_properties/carsharing-stations.csv
  carSharingFreeFloatingDataFile: data_clayton/zone_properties/carsharing-free-floating.csv
  #charging: unlimited
  defaultChargingPower: data_clayton/parameters/ChargingPower.txt
  zoneRepositoryFolder: output/zone-repository/
days: 1
modeChoice:
  firstTrip: data_clayton/parameters/ModeSelectorParameterFirstTrip.txt
  otherTrip: data_clayton/parameters/ModeSelectorParameterOtherTrip.txt
destinationChoice:
  repetition: data_clayton/parameters/TargetParameterRepetition.csv
  cost: data_clayton/parameters/TargetParameterCost.txt
fractionOfPopulation: 1
#numberOfZones: 1174
resultFolder: results/simulation
seed: 1234
visumFile: data_clayton/clayton/Clayton12km.net
experimental:
  externalTraffic: data_clayton/external_demand/demand-external.mtx
#  parameter2: 2